[package]
name = "fs-index"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.3.0"
fuzzy-matcher = "0.3.7"
ignore = "0.4.23"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
